# Generated by Django 6.0.2 on 2026-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmevent',
            name='silenced_at',
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='status',
            field=models.CharField(choices=[('RINGING', 'ringing'), ('CHECKED_IN', 'checked_in'), ('EXPIRED', 'expired')], default='RINGING', max_length=20),
        ),
    ]
