# Generated by Django 6.0.2 on 2026-03-11 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alarms.alarm'),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarms.group'),
        ),
        migrations.AddField(
            model_name='manualring',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_rings', to='alarms.alarm'),
        ),
        migrations.AddField(
            model_name='manualring',
            name='ringer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rings_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alarmevent',
            index=models.Index(fields=['alarm', '-created_at'], name='alarms_alar_alarm_i_9a03b5_idx'),
        ),
    ]
