# Generated by Django 6.0.2 on 2026-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='status',
            field=models.CharField(choices=[('RINGING', 'ringing'), ('SILENCED', 'silenced'), ('COMPLETED', 'completed'), ('EXPIRED', 'expired')], default='RINGING', max_length=20),
        ),
    ]
