# Generated by Django 6.0.2 on 2026-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='last_triggered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
