# Generated by Django 6.0.2 on 2026-02-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alter_alarm_id_alter_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='is_one_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='repeats',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
